<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260714075355 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cancellation_policy (id UUID NOT NULL, label VARCHAR(80) NOT NULL, rules JSONB NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE invoice (id UUID NOT NULL, number VARCHAR(30) NOT NULL, amount_ttc_cents INT NOT NULL, pdf_path VARCHAR(255) NOT NULL, issued_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, reservation_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9065174496901F54 ON invoice (number)');
        $this->addSql('CREATE INDEX IDX_90651744B83297E7 ON invoice (reservation_id)');
        $this->addSql('CREATE TABLE processed_webhook_event (stripe_event_id VARCHAR(60) NOT NULL, type VARCHAR(80) NOT NULL, processed_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (stripe_event_id))');
        $this->addSql('CREATE TABLE refund (id UUID NOT NULL, stripe_refund_id VARCHAR(50) NOT NULL, amount_cents INT NOT NULL, reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, reservation_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5B2C1458B83297E7 ON refund (reservation_id)');
        $this->addSql('CREATE TABLE reservation (id UUID NOT NULL, status VARCHAR(30) NOT NULL, appointment_starts_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, appointment_ends_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, price_ttc_cents INT NOT NULL, vat_rate NUMERIC(4, 2) NOT NULL, stripe_payment_intent_id VARCHAR(50) DEFAULT NULL, stripe_setup_intent_id VARCHAR(50) DEFAULT NULL, stripe_payment_method_id VARCHAR(50) DEFAULT NULL, idempotency_key VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, client_id UUID NOT NULL, service_id UUID NOT NULL, intervenant_id UUID NOT NULL, address_id UUID NOT NULL, cancellation_policy_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_42C849557FD1C147 ON reservation (idempotency_key)');
        $this->addSql('CREATE INDEX IDX_42C8495519EB6921 ON reservation (client_id)');
        $this->addSql('CREATE INDEX IDX_42C84955ED5CA9E6 ON reservation (service_id)');
        $this->addSql('CREATE INDEX IDX_42C84955AB9A1716 ON reservation (intervenant_id)');
        $this->addSql('CREATE INDEX IDX_42C84955F5B7AF75 ON reservation (address_id)');
        $this->addSql('CREATE INDEX IDX_42C84955F0C13F52 ON reservation (cancellation_policy_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_intervenant_appointment_starts_at ON reservation (intervenant_id, appointment_starts_at)');
        $this->addSql('CREATE TABLE reservation_status_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, from_status VARCHAR(30) DEFAULT NULL, to_status VARCHAR(30) NOT NULL, actor VARCHAR(10) NOT NULL, actor_id UUID DEFAULT NULL, reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, reservation_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A5E46F7B83297E7 ON reservation_status_history (reservation_id)');
        $this->addSql('CREATE TABLE slot_hold (id UUID NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, availability_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C1E3A79061778466 ON slot_hold (availability_id)');
        $this->addSql('CREATE INDEX IDX_C1E3A790A76ED395 ON slot_hold (user_id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT FK_5B2C1458B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C8495519EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955AB9A1716 FOREIGN KEY (intervenant_id) REFERENCES intervenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955F0C13F52 FOREIGN KEY (cancellation_policy_id) REFERENCES cancellation_policy (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation_status_history ADD CONSTRAINT FK_3A5E46F7B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE slot_hold ADD CONSTRAINT FK_C1E3A79061778466 FOREIGN KEY (availability_id) REFERENCES availability (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE slot_hold ADD CONSTRAINT FK_C1E3A790A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation_status_history ADD CONSTRAINT chk_history_actor CHECK (actor IN (\'CLIENT\', \'ADMIN\', \'SYSTEM\'))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE reservation_status_history DROP CONSTRAINT chk_history_actor');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_90651744B83297E7');
        $this->addSql('ALTER TABLE refund DROP CONSTRAINT FK_5B2C1458B83297E7');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C8495519EB6921');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955ED5CA9E6');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955AB9A1716');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955F5B7AF75');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955F0C13F52');
        $this->addSql('ALTER TABLE reservation_status_history DROP CONSTRAINT FK_3A5E46F7B83297E7');
        $this->addSql('ALTER TABLE slot_hold DROP CONSTRAINT FK_C1E3A79061778466');
        $this->addSql('ALTER TABLE slot_hold DROP CONSTRAINT FK_C1E3A790A76ED395');
        $this->addSql('DROP TABLE cancellation_policy');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE processed_webhook_event');
        $this->addSql('DROP TABLE refund');
        $this->addSql('DROP TABLE reservation');
        $this->addSql('DROP TABLE reservation_status_history');
        $this->addSql('DROP TABLE slot_hold');
    }
}
